language: cpp

compiler:
  - gcc

sudo: required

services:
  - docker

script: 
  - pwd && env && echo $PATH 
  - docker run -it -v `pwd`:/build-libhdfs3 --name=build-libhdfs3 ubuntu:14.04 bash -c 'cd /build-libhdfs3; debian/build.sh run'
